"""
Auto-generated COMPONENT_CATALOG for all 202 template components
Generated by generate_component_catalog.py
"""

COMPONENT_CATALOG = {
    "alerts/AlertError": {
        "description": "Error alert with red styling and warning icon",
        "keywords": ["alert", "notification", "message", "warning", "info", "error", "success", "error", "danger", "warning"],
        "type": "Alert"
    },
    "alerts/AlertInfo": {
        "description": "Info alert with blue styling and information icon",
        "keywords": ["alert", "notification", "message", "warning", "info", "error", "success", "info", "notice"],
        "type": "Alert"
    },
    "alerts/AlertSuccess": {
        "description": "Success alert with green styling and checkmark",
        "keywords": ["alert", "notification", "message", "warning", "info", "error", "success", "success", "confirmation"],
        "type": "Alert"
    },
    "alerts/AlertWarning": {
        "description": "Warning alert with yellow/orange styling",
        "keywords": ["alert", "notification", "message", "warning", "info", "error", "success", "warning", "caution"],
        "type": "Alert"
    },
    "alerts/BannerNotification": {
        "description": "Alert component",
        "keywords": ["alert", "notification", "message", "warning", "info", "error", "success"],
        "type": "Alert"
    },
    "alerts/NotificationToast": {
        "description": "Alert component",
        "keywords": ["alert", "notification", "message", "warning", "info", "error", "success"],
        "type": "Alert"
    },
    "blogs/BlogCards": {
        "description": "Blog component",
        "keywords": ["blog", "article", "post", "news", "content", "writing"],
        "type": "Blog"
    },
    "blogs/BlogFeatured": {
        "description": "Featured blog post with large image and detailed preview",
        "keywords": ["blog", "article", "post", "news", "content", "writing", "featured", "highlight"],
        "type": "Blog"
    },
    "blogs/BlogGrid": {
        "description": "Grid layout of blog posts with images and excerpts",
        "keywords": ["blog", "article", "post", "news", "content", "writing", "grid", "cards"],
        "type": "Blog"
    },
    "blogs/BlogList": {
        "description": "Vertical list of blog posts with metadata",
        "keywords": ["blog", "article", "post", "news", "content", "writing", "list", "vertical"],
        "type": "Blog"
    },
    "blogs/BlogMinimal": {
        "description": "Minimal blog list with clean typography",
        "keywords": ["blog", "article", "post", "news", "content", "writing", "minimal", "simple"],
        "type": "Blog"
    },
    "blogs/BlogTimeline": {
        "description": "Timeline-based blog layout with chronological ordering",
        "keywords": ["blog", "article", "post", "news", "content", "writing", "timeline", "chronological"],
        "type": "Blog"
    },
    "blogs/BlogWithSidebar": {
        "description": "Blog component",
        "keywords": ["blog", "article", "post", "news", "content", "writing"],
        "type": "Blog"
    },
    "cards/FeatureCardLarge": {
        "description": "Card component",
        "keywords": ["card", "content", "info", "preview"],
        "type": "Card"
    },
    "cards/IconCards": {
        "description": "Card component",
        "keywords": ["card", "content", "info", "preview"],
        "type": "Card"
    },
    "cards/ImageCard": {
        "description": "Card component",
        "keywords": ["card", "content", "info", "preview"],
        "type": "Card"
    },
    "cards/InfoCards": {
        "description": "Card component",
        "keywords": ["card", "content", "info", "preview"],
        "type": "Card"
    },
    "cards/NewsCard": {
        "description": "Card component",
        "keywords": ["card", "content", "info", "preview"],
        "type": "Card"
    },
    "cards/PricingCardSimple": {
        "description": "Card component",
        "keywords": ["card", "content", "info", "preview"],
        "type": "Card"
    },
    "cards/ProfileCard": {
        "description": "Card component",
        "keywords": ["card", "content", "info", "preview"],
        "type": "Card"
    },
    "cards/ServiceCards": {
        "description": "Card component",
        "keywords": ["card", "content", "info", "preview"],
        "type": "Card"
    },
    "cards/StatCard": {
        "description": "Card component",
        "keywords": ["card", "content", "info", "preview"],
        "type": "Card"
    },
    "cards/TestimonialCardCompact": {
        "description": "Card component",
        "keywords": ["card", "content", "info", "preview"],
        "type": "Card"
    },
    "contacts/ContactCards": {
        "description": "Contact component",
        "keywords": ["contact", "form", "get in touch", "reach us", "email"],
        "type": "Contact"
    },
    "contacts/ContactCentered": {
        "description": "Contact component",
        "keywords": ["contact", "form", "get in touch", "reach us", "email"],
        "type": "Contact"
    },
    "contacts/ContactFullPage": {
        "description": "Contact component",
        "keywords": ["contact", "form", "get in touch", "reach us", "email"],
        "type": "Contact"
    },
    "contacts/ContactMinimal": {
        "description": "Minimal contact form with essential fields only",
        "keywords": ["contact", "form", "get in touch", "reach us", "email", "minimal", "simple"],
        "type": "Contact"
    },
    "contacts/ContactSimple": {
        "description": "Contact component",
        "keywords": ["contact", "form", "get in touch", "reach us", "email"],
        "type": "Contact"
    },
    "contacts/ContactSplit": {
        "description": "Split layout with form and contact info side-by-side",
        "keywords": ["contact", "form", "get in touch", "reach us", "email", "split", "two-column"],
        "type": "Contact"
    },
    "contacts/ContactWithInfo": {
        "description": "Contact component",
        "keywords": ["contact", "form", "get in touch", "reach us", "email"],
        "type": "Contact"
    },
    "contacts/ContactWithTeam": {
        "description": "Contact component",
        "keywords": ["contact", "form", "get in touch", "reach us", "email"],
        "type": "Contact"
    },
    "ctas/CTABanner": {
        "description": "Full-width banner CTA with prominent styling",
        "keywords": ["cta", "call to action", "signup", "get started", "button", "banner", "full-width"],
        "type": "CTA"
    },
    "ctas/CTABoxed": {
        "description": "Boxed CTA with border and background",
        "keywords": ["cta", "call to action", "signup", "get started", "button", "boxed", "container"],
        "type": "CTA"
    },
    "ctas/CTAFullWidth": {
        "description": "CTA component",
        "keywords": ["cta", "call to action", "signup", "get started", "button"],
        "type": "CTA"
    },
    "ctas/CTAMinimal": {
        "description": "Minimal CTA with clean design",
        "keywords": ["cta", "call to action", "signup", "get started", "button", "minimal", "clean"],
        "type": "CTA"
    },
    "ctas/CTASimple": {
        "description": "Simple CTA with headline and button",
        "keywords": ["cta", "call to action", "signup", "get started", "button", "simple", "basic"],
        "type": "CTA"
    },
    "ctas/CTATwoButton": {
        "description": "CTA component",
        "keywords": ["cta", "call to action", "signup", "get started", "button"],
        "type": "CTA"
    },
    "ctas/CTAWithImage": {
        "description": "CTA section with supporting image or icon",
        "keywords": ["cta", "call to action", "signup", "get started", "button", "image", "visual"],
        "type": "CTA"
    },
    "ctas/CTAWithStats": {
        "description": "CTA component",
        "keywords": ["cta", "call to action", "signup", "get started", "button"],
        "type": "CTA"
    },
    "ecommerce/CartSummary": {
        "description": "Ecommerce component",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart"],
        "type": "Ecommerce"
    },
    "ecommerce/CheckoutSteps": {
        "description": "Ecommerce component",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart"],
        "type": "Ecommerce"
    },
    "ecommerce/ProductBadges": {
        "description": "Ecommerce component",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart"],
        "type": "Ecommerce"
    },
    "ecommerce/ProductCarousel": {
        "description": "Ecommerce component",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart"],
        "type": "Ecommerce"
    },
    "ecommerce/ProductCompare": {
        "description": "Ecommerce component",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart"],
        "type": "Ecommerce"
    },
    "ecommerce/ProductFilters": {
        "description": "Product filtering and sorting interface",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart", "filter", "sort", "search"],
        "type": "Ecommerce"
    },
    "ecommerce/ProductGrid": {
        "description": "Grid of products with images, prices, and add to cart",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart", "grid", "catalog"],
        "type": "Ecommerce"
    },
    "ecommerce/ProductQuickView": {
        "description": "Quick view modal for products",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart", "quickview", "modal"],
        "type": "Ecommerce"
    },
    "ecommerce/ProductRatingStars": {
        "description": "Ecommerce component",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart"],
        "type": "Ecommerce"
    },
    "ecommerce/ProductReviews": {
        "description": "Product reviews and ratings section",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart", "reviews", "ratings"],
        "type": "Ecommerce"
    },
    "ecommerce/ProductShowcase": {
        "description": "Ecommerce component",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart"],
        "type": "Ecommerce"
    },
    "ecommerce/ProductWishlist": {
        "description": "Ecommerce component",
        "keywords": ["ecommerce", "shop", "store", "product", "buy", "cart"],
        "type": "Ecommerce"
    },
    "faqs/FAQAccordion": {
        "description": "FAQ section with accordion-style expandable items",
        "keywords": ["faq", "questions", "answers", "help", "support", "accordion", "collapsible"],
        "type": "FAQ"
    },
    "faqs/FAQMinimal": {
        "description": "Minimal FAQ list with simple styling",
        "keywords": ["faq", "questions", "answers", "help", "support", "minimal", "simple"],
        "type": "FAQ"
    },
    "faqs/FAQSimple": {
        "description": "FAQ component",
        "keywords": ["faq", "questions", "answers", "help", "support"],
        "type": "FAQ"
    },
    "faqs/FAQTwoColumn": {
        "description": "FAQ component",
        "keywords": ["faq", "questions", "answers", "help", "support"],
        "type": "FAQ"
    },
    "faqs/FAQWithCTA": {
        "description": "FAQ component",
        "keywords": ["faq", "questions", "answers", "help", "support"],
        "type": "FAQ"
    },
    "features/FeaturesAlternating": {
        "description": "Alternating layout with images and text",
        "keywords": ["features", "services", "benefits", "offerings", "what we do", "alternating", "image"],
        "type": "Features"
    },
    "features/FeaturesCompact": {
        "description": "Compact features layout for quick scanning",
        "keywords": ["features", "services", "benefits", "offerings", "what we do", "compact", "dense"],
        "type": "Features"
    },
    "features/FeaturesGrid": {
        "description": "Grid layout of features with icons and descriptions",
        "keywords": ["features", "services", "benefits", "offerings", "what we do", "grid", "cards"],
        "type": "Features"
    },
    "features/FeaturesList": {
        "description": "Vertical list of features with detailed descriptions",
        "keywords": ["features", "services", "benefits", "offerings", "what we do", "list", "vertical"],
        "type": "Features"
    },
    "features/FeaturesWithIcons": {
        "description": "Features highlighted with custom icons",
        "keywords": ["features", "services", "benefits", "offerings", "what we do", "icons", "visual"],
        "type": "Features"
    },
    "footers/FooterCentered": {
        "description": "Centered footer layout",
        "keywords": ["footer", "bottom", "links", "copyright", "social", "centered", "symmetric"],
        "type": "Footer"
    },
    "footers/FooterComprehensive": {
        "description": "Full footer with multiple columns, links, and social media",
        "keywords": ["footer", "bottom", "links", "copyright", "social", "comprehensive", "full", "detailed"],
        "type": "Footer"
    },
    "footers/FooterDark": {
        "description": "Footer component",
        "keywords": ["footer", "bottom", "links", "copyright", "social"],
        "type": "Footer"
    },
    "footers/FooterLarge": {
        "description": "Footer component",
        "keywords": ["footer", "bottom", "links", "copyright", "social"],
        "type": "Footer"
    },
    "footers/FooterMinimal": {
        "description": "Minimal footer with brand name and basic links",
        "keywords": ["footer", "bottom", "links", "copyright", "social", "minimal", "simple", "clean"],
        "type": "Footer"
    },
    "footers/FooterNewsletter": {
        "description": "Footer with newsletter signup",
        "keywords": ["footer", "bottom", "links", "copyright", "social", "newsletter", "subscribe"],
        "type": "Footer"
    },
    "footers/FooterSimple": {
        "description": "Simple single-line footer",
        "keywords": ["footer", "bottom", "links", "copyright", "social", "simple", "compact"],
        "type": "Footer"
    },
    "footers/FooterWithMap": {
        "description": "Footer component",
        "keywords": ["footer", "bottom", "links", "copyright", "social"],
        "type": "Footer"
    },
    "forms/ApplicationForm": {
        "description": "Form component",
        "keywords": ["form", "input", "submit", "fields"],
        "type": "Form"
    },
    "forms/ContactFormInline": {
        "description": "Form component",
        "keywords": ["form", "input", "submit", "fields"],
        "type": "Form"
    },
    "forms/FeedbackForm": {
        "description": "Form component",
        "keywords": ["form", "input", "submit", "fields"],
        "type": "Form"
    },
    "forms/LoginForm": {
        "description": "Form component",
        "keywords": ["form", "input", "submit", "fields"],
        "type": "Form"
    },
    "forms/MultiStepForm": {
        "description": "Form component",
        "keywords": ["form", "input", "submit", "fields"],
        "type": "Form"
    },
    "forms/QuoteForm": {
        "description": "Form component",
        "keywords": ["form", "input", "submit", "fields"],
        "type": "Form"
    },
    "forms/SignupForm": {
        "description": "Form component",
        "keywords": ["form", "input", "submit", "fields"],
        "type": "Form"
    },
    "forms/SubscribeForm": {
        "description": "Form component",
        "keywords": ["form", "input", "submit", "fields"],
        "type": "Form"
    },
    "galleries/GalleryFullWidth": {
        "description": "Gallery component",
        "keywords": ["gallery", "images", "photos", "portfolio", "showcase"],
        "type": "Gallery"
    },
    "galleries/GalleryGrid": {
        "description": "Grid-based image gallery",
        "keywords": ["gallery", "images", "photos", "portfolio", "showcase", "grid", "uniform"],
        "type": "Gallery"
    },
    "galleries/GalleryHover": {
        "description": "Gallery component",
        "keywords": ["gallery", "images", "photos", "portfolio", "showcase"],
        "type": "Gallery"
    },
    "galleries/GalleryLightbox": {
        "description": "Gallery with lightbox/modal image viewer",
        "keywords": ["gallery", "images", "photos", "portfolio", "showcase", "lightbox", "modal", "popup"],
        "type": "Gallery"
    },
    "galleries/GalleryMasonry": {
        "description": "Masonry-style gallery with varied image sizes",
        "keywords": ["gallery", "images", "photos", "portfolio", "showcase", "masonry", "pinterest"],
        "type": "Gallery"
    },
    "galleries/GalleryPortfolio": {
        "description": "Gallery component",
        "keywords": ["gallery", "images", "photos", "portfolio", "showcase"],
        "type": "Gallery"
    },
    "galleries/GallerySlider": {
        "description": "Gallery component",
        "keywords": ["gallery", "images", "photos", "portfolio", "showcase"],
        "type": "Gallery"
    },
    "galleries/GalleryWithTabs": {
        "description": "Gallery component",
        "keywords": ["gallery", "images", "photos", "portfolio", "showcase"],
        "type": "Gallery"
    },
    "headers/HeaderCentered": {
        "description": "Centered header layout",
        "keywords": ["header", "navigation", "nav", "menu", "top", "centered", "symmetric"],
        "type": "Header"
    },
    "headers/HeaderMegaMenu": {
        "description": "Header component",
        "keywords": ["header", "navigation", "nav", "menu", "top"],
        "type": "Header"
    },
    "headers/HeaderMinimal": {
        "description": "Minimal header with logo and basic navigation",
        "keywords": ["header", "navigation", "nav", "menu", "top", "minimal", "simple"],
        "type": "Header"
    },
    "headers/HeaderSticky": {
        "description": "Sticky header that stays at top when scrolling",
        "keywords": ["header", "navigation", "nav", "menu", "top", "sticky", "fixed"],
        "type": "Header"
    },
    "headers/HeaderTransparent": {
        "description": "Transparent header for hero overlays",
        "keywords": ["header", "navigation", "nav", "menu", "top", "transparent", "overlay"],
        "type": "Header"
    },
    "headers/HeaderWithAuth": {
        "description": "Header component",
        "keywords": ["header", "navigation", "nav", "menu", "top"],
        "type": "Header"
    },
    "headers/HeaderWithCTA": {
        "description": "Header with navigation and call-to-action button",
        "keywords": ["header", "navigation", "nav", "menu", "top", "cta", "button"],
        "type": "Header"
    },
    "headers/HeaderWithSearch": {
        "description": "Header with integrated search bar",
        "keywords": ["header", "navigation", "nav", "menu", "top", "search", "find"],
        "type": "Header"
    },
    "heroes/HeroAnimated": {
        "description": "Hero with animated elements",
        "keywords": ["hero", "banner", "landing", "headline", "main", "animated", "motion"],
        "type": "Hero"
    },
    "heroes/HeroCentered": {
        "description": "Centered hero with headline and call-to-action",
        "keywords": ["hero", "banner", "landing", "headline", "main", "centered", "symmetric"],
        "type": "Hero"
    },
    "heroes/HeroFullHeight": {
        "description": "Hero component",
        "keywords": ["hero", "banner", "landing", "headline", "main"],
        "type": "Hero"
    },
    "heroes/HeroGradient": {
        "description": "Hero with gradient background",
        "keywords": ["hero", "banner", "landing", "headline", "main", "gradient", "color"],
        "type": "Hero"
    },
    "heroes/HeroImage": {
        "description": "Hero section with headline, CTA, and image",
        "keywords": ["hero", "banner", "landing", "headline", "main", "image", "visual"],
        "type": "Hero"
    },
    "heroes/HeroMinimal": {
        "description": "Minimal hero with essential elements only",
        "keywords": ["hero", "banner", "landing", "headline", "main", "minimal", "simple"],
        "type": "Hero"
    },
    "heroes/HeroSplit": {
        "description": "Split hero with content and image side-by-side",
        "keywords": ["hero", "banner", "landing", "headline", "main", "split", "two-column"],
        "type": "Hero"
    },
    "heroes/HeroVideo": {
        "description": "Hero with background video",
        "keywords": ["hero", "banner", "landing", "headline", "main", "video", "media"],
        "type": "Hero"
    },
    "heroes/HeroWithForm": {
        "description": "Hero section with embedded form",
        "keywords": ["hero", "banner", "landing", "headline", "main", "form", "signup"],
        "type": "Hero"
    },
    "heroes/HeroWithStats": {
        "description": "Hero component",
        "keywords": ["hero", "banner", "landing", "headline", "main"],
        "type": "Hero"
    },
    "logos/ClientLogos": {
        "description": "LogoGrid component",
        "keywords": ["logo", "brands", "partners", "clients", "companies"],
        "type": "LogoGrid"
    },
    "logos/LogoGrid": {
        "description": "LogoGrid component",
        "keywords": ["logo", "brands", "partners", "clients", "companies"],
        "type": "LogoGrid"
    },
    "logos/PartnerLogos": {
        "description": "LogoGrid component",
        "keywords": ["logo", "brands", "partners", "clients", "companies"],
        "type": "LogoGrid"
    },
    "misc/BackToTop": {
        "description": "Back to top button",
        "keywords": ["utility", "helper", "component", "scroll", "top", "up"],
        "type": "Utility"
    },
    "misc/ComingSoon": {
        "description": "Utility component",
        "keywords": ["utility", "helper", "component"],
        "type": "Utility"
    },
    "misc/Cookie Banner": {
        "description": "Utility component",
        "keywords": ["utility", "helper", "component"],
        "type": "Utility"
    },
    "misc/CountdownTimer": {
        "description": "Countdown timer component",
        "keywords": ["utility", "helper", "component", "countdown", "timer", "deadline"],
        "type": "Utility"
    },
    "misc/Divider": {
        "description": "Visual divider/separator component",
        "keywords": ["utility", "helper", "component", "divider", "separator", "line"],
        "type": "Utility"
    },
    "misc/EmailSignature": {
        "description": "Email signature component",
        "keywords": ["utility", "helper", "component", "email", "signature", "contact"],
        "type": "Utility"
    },
    "misc/ErrorPage": {
        "description": "Utility component",
        "keywords": ["utility", "helper", "component"],
        "type": "Utility"
    },
    "misc/LanguageSelector": {
        "description": "Utility component",
        "keywords": ["utility", "helper", "component"],
        "type": "Utility"
    },
    "misc/LiveChat": {
        "description": "Live chat widget placeholder",
        "keywords": ["utility", "helper", "component", "chat", "support", "help"],
        "type": "Utility"
    },
    "misc/LoadingScreen": {
        "description": "Utility component",
        "keywords": ["utility", "helper", "component"],
        "type": "Utility"
    },
    "misc/MaintenanceMode": {
        "description": "Utility component",
        "keywords": ["utility", "helper", "component"],
        "type": "Utility"
    },
    "misc/PrintButton": {
        "description": "Print page button",
        "keywords": ["utility", "helper", "component", "print", "pdf"],
        "type": "Utility"
    },
    "misc/QRCode": {
        "description": "QR code display component",
        "keywords": ["utility", "helper", "component", "qr", "code", "scan"],
        "type": "Utility"
    },
    "misc/QuickLinks": {
        "description": "Utility component",
        "keywords": ["utility", "helper", "component"],
        "type": "Utility"
    },
    "misc/ReadingTime": {
        "description": "Reading time estimate display",
        "keywords": ["utility", "helper", "component", "reading", "time", "estimate"],
        "type": "Utility"
    },
    "misc/ScrollProgress": {
        "description": "Utility component",
        "keywords": ["utility", "helper", "component"],
        "type": "Utility"
    },
    "misc/ShareButtons": {
        "description": "Social share buttons",
        "keywords": ["utility", "helper", "component", "share", "social", "media"],
        "type": "Utility"
    },
    "misc/SkipToContent": {
        "description": "Accessibility skip to content link",
        "keywords": ["utility", "helper", "component", "accessibility", "a11y", "skip"],
        "type": "Utility"
    },
    "misc/Spacer": {
        "description": "Utility component",
        "keywords": ["utility", "helper", "component"],
        "type": "Utility"
    },
    "misc/ThemeToggle": {
        "description": "Dark/light theme toggle",
        "keywords": ["utility", "helper", "component", "theme", "dark", "light"],
        "type": "Utility"
    },
    "modals/ModalSimple": {
        "description": "Modal component",
        "keywords": ["modal", "popup", "dialog", "overlay"],
        "type": "Modal"
    },
    "modals/ModalWithForm": {
        "description": "Modal component",
        "keywords": ["modal", "popup", "dialog", "overlay"],
        "type": "Modal"
    },
    "modals/PopupNotification": {
        "description": "Modal component",
        "keywords": ["modal", "popup", "dialog", "overlay"],
        "type": "Modal"
    },
    "navigation/Breadcrumbs": {
        "description": "Navigation component",
        "keywords": ["navigation", "nav", "menu", "links"],
        "type": "Navigation"
    },
    "navigation/FooterNav": {
        "description": "Navigation component",
        "keywords": ["navigation", "nav", "menu", "links"],
        "type": "Navigation"
    },
    "navigation/MobileMenu": {
        "description": "Navigation component",
        "keywords": ["navigation", "nav", "menu", "links"],
        "type": "Navigation"
    },
    "navigation/Pagination": {
        "description": "Navigation component",
        "keywords": ["navigation", "nav", "menu", "links"],
        "type": "Navigation"
    },
    "navigation/Sidebar": {
        "description": "Navigation component",
        "keywords": ["navigation", "nav", "menu", "links"],
        "type": "Navigation"
    },
    "navigation/TabNavigation": {
        "description": "Navigation component",
        "keywords": ["navigation", "nav", "menu", "links"],
        "type": "Navigation"
    },
    "newsletters/NewsletterBoxed": {
        "description": "Newsletter component",
        "keywords": ["newsletter", "subscribe", "email", "signup"],
        "type": "Newsletter"
    },
    "newsletters/NewsletterFullWidth": {
        "description": "Newsletter component",
        "keywords": ["newsletter", "subscribe", "email", "signup"],
        "type": "Newsletter"
    },
    "newsletters/NewsletterInline": {
        "description": "Inline newsletter form for embedding",
        "keywords": ["newsletter", "subscribe", "email", "signup", "inline", "embedded"],
        "type": "Newsletter"
    },
    "newsletters/NewsletterMinimal": {
        "description": "Minimal newsletter signup",
        "keywords": ["newsletter", "subscribe", "email", "signup", "minimal", "clean"],
        "type": "Newsletter"
    },
    "newsletters/NewsletterPopup": {
        "description": "Newsletter popup/modal",
        "keywords": ["newsletter", "subscribe", "email", "signup", "popup", "modal"],
        "type": "Newsletter"
    },
    "newsletters/NewsletterSimple": {
        "description": "Simple newsletter signup with email input",
        "keywords": ["newsletter", "subscribe", "email", "signup", "simple", "basic"],
        "type": "Newsletter"
    },
    "newsletters/NewsletterWithBenefits": {
        "description": "Newsletter signup highlighting benefits",
        "keywords": ["newsletter", "subscribe", "email", "signup", "benefits", "features"],
        "type": "Newsletter"
    },
    "pricing/PricingCards": {
        "description": "Pricing table with multiple plan tiers",
        "keywords": ["pricing", "plans", "subscription", "tiers", "cost", "cards", "tiers"],
        "type": "Pricing"
    },
    "pricing/PricingCompact": {
        "description": "Pricing component",
        "keywords": ["pricing", "plans", "subscription", "tiers", "cost"],
        "type": "Pricing"
    },
    "pricing/PricingSimple": {
        "description": "Pricing component",
        "keywords": ["pricing", "plans", "subscription", "tiers", "cost"],
        "type": "Pricing"
    },
    "pricing/PricingToggle": {
        "description": "Pricing with monthly/yearly toggle",
        "keywords": ["pricing", "plans", "subscription", "tiers", "cost", "toggle", "switch"],
        "type": "Pricing"
    },
    "progress/LoadingDots": {
        "description": "Progress component",
        "keywords": ["progress", "loading", "steps", "status"],
        "type": "Progress"
    },
    "progress/LoadingSpinner": {
        "description": "Progress component",
        "keywords": ["progress", "loading", "steps", "status"],
        "type": "Progress"
    },
    "progress/ProgressBar": {
        "description": "Linear progress bar",
        "keywords": ["progress", "loading", "steps", "status", "bar", "linear"],
        "type": "Progress"
    },
    "progress/StepIndicator": {
        "description": "Progress component",
        "keywords": ["progress", "loading", "steps", "status"],
        "type": "Progress"
    },
    "restaurant/ChefProfile": {
        "description": "Chef profile section",
        "keywords": ["restaurant", "menu", "food", "dining", "cafe", "chef", "team", "about"],
        "type": "Restaurant"
    },
    "restaurant/DailySpecials": {
        "description": "Restaurant component",
        "keywords": ["restaurant", "menu", "food", "dining", "cafe"],
        "type": "Restaurant"
    },
    "restaurant/HoursLocation": {
        "description": "Restaurant hours and location info",
        "keywords": ["restaurant", "menu", "food", "dining", "cafe", "hours", "location", "address"],
        "type": "Restaurant"
    },
    "restaurant/MenuCategories": {
        "description": "Menu organized by food categories",
        "keywords": ["restaurant", "menu", "food", "dining", "cafe", "categories", "sections"],
        "type": "Restaurant"
    },
    "restaurant/MenuSection": {
        "description": "Restaurant component",
        "keywords": ["restaurant", "menu", "food", "dining", "cafe"],
        "type": "Restaurant"
    },
    "restaurant/ReservationForm": {
        "description": "Table reservation form",
        "keywords": ["restaurant", "menu", "food", "dining", "cafe", "reservation", "booking", "table"],
        "type": "Restaurant"
    },
    "restaurant/RestaurantGallery": {
        "description": "Restaurant component",
        "keywords": ["restaurant", "menu", "food", "dining", "cafe"],
        "type": "Restaurant"
    },
    "restaurant/ReviewsRatings": {
        "description": "Restaurant component",
        "keywords": ["restaurant", "menu", "food", "dining", "cafe"],
        "type": "Restaurant"
    },
    "restaurant/SpecialOffers": {
        "description": "Restaurant component",
        "keywords": ["restaurant", "menu", "food", "dining", "cafe"],
        "type": "Restaurant"
    },
    "restaurant/TableBooking": {
        "description": "Restaurant component",
        "keywords": ["restaurant", "menu", "food", "dining", "cafe"],
        "type": "Restaurant"
    },
    "saas/APIDocumentation": {
        "description": "API documentation section",
        "keywords": ["saas", "software", "platform", "app", "tool", "api", "docs", "developers"],
        "type": "SaaS"
    },
    "saas/Dashboard Preview": {
        "description": "SaaS component",
        "keywords": ["saas", "software", "platform", "app", "tool"],
        "type": "SaaS"
    },
    "saas/FeatureComparison": {
        "description": "SaaS component",
        "keywords": ["saas", "software", "platform", "app", "tool"],
        "type": "SaaS"
    },
    "saas/IntegrationLogos": {
        "description": "SaaS component",
        "keywords": ["saas", "software", "platform", "app", "tool"],
        "type": "SaaS"
    },
    "saas/SaaSChangelog": {
        "description": "SaaS component",
        "keywords": ["saas", "software", "platform", "app", "tool"],
        "type": "SaaS"
    },
    "saas/SaaSFeatureList": {
        "description": "SaaS component",
        "keywords": ["saas", "software", "platform", "app", "tool"],
        "type": "SaaS"
    },
    "saas/SaaSMetrics": {
        "description": "SaaS component",
        "keywords": ["saas", "software", "platform", "app", "tool"],
        "type": "SaaS"
    },
    "saas/SaaSSecurityBadges": {
        "description": "SaaS component",
        "keywords": ["saas", "software", "platform", "app", "tool"],
        "type": "SaaS"
    },
    "saas/SaaSStatusPage": {
        "description": "SaaS component",
        "keywords": ["saas", "software", "platform", "app", "tool"],
        "type": "SaaS"
    },
    "saas/SaaSUseCases": {
        "description": "SaaS component",
        "keywords": ["saas", "software", "platform", "app", "tool"],
        "type": "SaaS"
    },
    "search/SearchAutocomplete": {
        "description": "Search component",
        "keywords": ["search", "find", "filter", "query"],
        "type": "Search"
    },
    "search/SearchBar": {
        "description": "Search bar with autocomplete",
        "keywords": ["search", "find", "filter", "query", "bar", "autocomplete"],
        "type": "Search"
    },
    "search/SearchWithFilters": {
        "description": "Search with advanced filters",
        "keywords": ["search", "find", "filter", "query", "filters", "advanced"],
        "type": "Search"
    },
    "social/SocialFollow": {
        "description": "Social component",
        "keywords": ["social", "media", "share", "follow"],
        "type": "Social"
    },
    "social/SocialLinks": {
        "description": "Social media links with icons",
        "keywords": ["social", "media", "share", "follow", "links", "icons"],
        "type": "Social"
    },
    "social/SocialShare": {
        "description": "Social share buttons",
        "keywords": ["social", "media", "share", "follow", "share", "buttons"],
        "type": "Social"
    },
    "stats/StatsCounter": {
        "description": "Stats component",
        "keywords": ["stats", "statistics", "numbers", "metrics", "achievements"],
        "type": "Stats"
    },
    "stats/StatsGrid": {
        "description": "Grid of statistics with numbers and labels",
        "keywords": ["stats", "statistics", "numbers", "metrics", "achievements", "grid", "cards"],
        "type": "Stats"
    },
    "stats/StatsLarge": {
        "description": "Stats component",
        "keywords": ["stats", "statistics", "numbers", "metrics", "achievements"],
        "type": "Stats"
    },
    "stats/StatsMinimal": {
        "description": "Minimal statistics display",
        "keywords": ["stats", "statistics", "numbers", "metrics", "achievements", "minimal", "clean"],
        "type": "Stats"
    },
    "stats/StatsWithHeadline": {
        "description": "Stats component",
        "keywords": ["stats", "statistics", "numbers", "metrics", "achievements"],
        "type": "Stats"
    },
    "tabs/AccordionMultiple": {
        "description": "Tabs component",
        "keywords": ["tabs", "tabbed", "panels", "sections"],
        "type": "Tabs"
    },
    "tabs/TabsSimple": {
        "description": "Tabs component",
        "keywords": ["tabs", "tabbed", "panels", "sections"],
        "type": "Tabs"
    },
    "tabs/TabsVertical": {
        "description": "Vertical tabs layout",
        "keywords": ["tabs", "tabbed", "panels", "sections", "vertical", "sidebar"],
        "type": "Tabs"
    },
    "teams/TeamGrid": {
        "description": "Grid of team members with photos and bios",
        "keywords": ["team", "staff", "members", "people", "about us", "grid", "cards"],
        "type": "Team"
    },
    "teams/TeamLarge": {
        "description": "Team component",
        "keywords": ["team", "staff", "members", "people", "about us"],
        "type": "Team"
    },
    "teams/TeamMinimal": {
        "description": "Minimal team display",
        "keywords": ["team", "staff", "members", "people", "about us", "minimal", "simple"],
        "type": "Team"
    },
    "teams/TeamWithSocial": {
        "description": "Team members with social links",
        "keywords": ["team", "staff", "members", "people", "about us", "social", "links"],
        "type": "Team"
    },
    "testimonials/TestimonialsCarousel": {
        "description": "Carousel of testimonials",
        "keywords": ["testimonials", "reviews", "feedback", "customers", "quotes", "carousel", "slider"],
        "type": "Testimonials"
    },
    "testimonials/TestimonialsGrid": {
        "description": "Grid of customer testimonials",
        "keywords": ["testimonials", "reviews", "feedback", "customers", "quotes", "grid", "cards"],
        "type": "Testimonials"
    },
    "testimonials/TestimonialsSingle": {
        "description": "Testimonials component",
        "keywords": ["testimonials", "reviews", "feedback", "customers", "quotes"],
        "type": "Testimonials"
    },
    "testimonials/TestimonialsWithPhotos": {
        "description": "Testimonials component",
        "keywords": ["testimonials", "reviews", "feedback", "customers", "quotes"],
        "type": "Testimonials"
    },
    "timelines/MilestoneTimeline": {
        "description": "Timeline component",
        "keywords": ["timeline", "history", "chronological", "roadmap", "milestones"],
        "type": "Timeline"
    },
    "timelines/ProcessSteps": {
        "description": "Timeline component",
        "keywords": ["timeline", "history", "chronological", "roadmap", "milestones"],
        "type": "Timeline"
    },
    "timelines/RoadmapTimeline": {
        "description": "Timeline component",
        "keywords": ["timeline", "history", "chronological", "roadmap", "milestones"],
        "type": "Timeline"
    },
    "timelines/TimelineHorizontal": {
        "description": "Horizontal timeline",
        "keywords": ["timeline", "history", "chronological", "roadmap", "milestones", "horizontal", "linear"],
        "type": "Timeline"
    },
    "timelines/TimelineVertical": {
        "description": "Vertical timeline with dates and events",
        "keywords": ["timeline", "history", "chronological", "roadmap", "milestones", "vertical", "chronological"],
        "type": "Timeline"
    },
    "videos/VideoBackground": {
        "description": "Video component",
        "keywords": ["video", "media", "youtube", "vimeo", "player"],
        "type": "Video"
    },
    "videos/VideoEmbed": {
        "description": "Embedded video player",
        "keywords": ["video", "media", "youtube", "vimeo", "player", "embed", "player"],
        "type": "Video"
    },
    "videos/VideoGallery": {
        "description": "Video component",
        "keywords": ["video", "media", "youtube", "vimeo", "player"],
        "type": "Video"
    },
    "videos/VideoHero": {
        "description": "Video background hero section",
        "keywords": ["video", "media", "youtube", "vimeo", "player", "hero", "background"],
        "type": "Video"
    },
    "videos/VideoTestimonial": {
        "description": "Video testimonial player",
        "keywords": ["video", "media", "youtube", "vimeo", "player", "testimonial", "review"],
        "type": "Video"
    },
}